version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    networks:
      - app_default

  llm_service:
    build:
      context: ./backend/llm_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    working_dir: /app
    volumes:
      - ./backend/llm_service/app:/app
    env_file:
      - .env  # Load environment variables from main project folder
    depends_on:
      - db
      - backend
    networks:
      - app_default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_default

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: liat
      POSTGRES_PASSWORD: liat2003
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_default

volumes:
  postgres_data:

networks:
  app_default:
    driver: bridge
